### ISSUE TITLE
Slack org?

### ISSUE THREAD

**Issue by NoodlesNZ** [PHPJubilee/Project#7]
It'd be good to get a Slack org setup to allow discussion over a project. I see that PHPJubilee.slack.com has already been registered, so I assume you're one setup ahead of me, but can you start inviting us into it?
Thanks

**Comment by JordanRL** [comment]
I didn't set up that slack channel. I don't know who did.

I did set up a gitter channel though.

https://gitter.im/PHPJubilee

**Comment by matthewtrask** [comment]
It would be cool to get on Slack, just cause theres a lot of people already on there. Plus Im bad about checking Gitter.

**Comment by NoodlesNZ** [comment]
Ok, I've created a Slack org for those interested. Email me at nick [at] noodles [dot] net.nz and I'll add you into the team.

**Comment by saji89** [comment]
@NoodlesNZ @JordanRL @rocketpastsix 
Sorry guys... I had created that for testing the possibility of using slack.
I did some initial analysis, forgot about it later, that is why I didn't post here.

Its the first time Iam using slack. @JordanRL I can add you as the owner of the team.

**Comment by saji89** [comment]
@JordanRL I have send request to add you to the slack domain. 

@all others, Looks like we need the email id to add people to slack.

**Comment by NoodlesNZ** [comment]
@saji89 my email is above, can you invite me please?

**Comment by JordanRL** [comment]
Well, I think we should decide which service we would like to use sometime soon, but for now I will be in all three.

I don't see a reason not to keep the IRC channel open (I rather like IRC), but we should eventually choose between gitter and slack.

**Comment by saji89** [comment]
@NoodlesNZ Invited you.

**Comment by saji89** [comment]
@JordanRL Overall Slack seems to offer more integrations and has more features. Definitely we should choose one among Slack and Gitter, going ahead.

Initial advantage of gitter is that it is directly linked with Github, so no need to invite members.

**Comment by naroga** [comment]
I don't really care for Gitter or Slack, as long as all relevant discussion gets summarized and posted somewhere 'permanent' to be available to everyone. I'm always on the IRC channel (I too really like IRC), but the issue with it is availability of decisions.

I feel like a forum format would be more suited than a log-keeping-chat to make decisions available to everyone and IRC would be more suited for timely questions. We're kind of doing it already, but using issues (!) on github instead of threads in a forum, which strikes me as a weird decision.

**Comment by saji89** [comment]
@naroga As far as I know. Slack keeps the whole log of discussions, for the life of the channel.
Gitter also offers unlimited chat history.

**Comment by naroga** [comment]
@saji89 it does, but it's a chat. It won't aggregate same-subject discussions into threads, nor will it be a sane repository for late-joining members to get up-to-date on the project decisions. Decisions made on Slack/Gitter will have to be summarized and posted somewhere else in an organized fashion.

IMHO IRC is enough as a chat. Most people from FOSS projects use it (freenode is a server dedicated to open source development), it's much more 'dinamic' for timely questions/general conversation, and github issues may be enough for threaded conversation. I don't like the idea of using 'issues' as 'threads', but I also don't think there is a need for bloating our process with another tool.

I'll go with whatever you guys decide, but that's my 2 cents.

**Comment by szainmehdi** [comment]
Have we made a decision yet on the preferred chat client yet?

**Comment by NoodlesNZ** [comment]
I haven't seen any activity in IRC yet, with the different timezones and work schedules I think Slack is easier as it keeps a searchable archive.

**Comment by saji89** [comment]
Slack, Definitely looks the better option, at the moment, its Github integration and other general features are pretty good.

**Comment by dersam** [comment]
I think Gitter is the best choice.  Since one of the stated goals of this project was to get people contributing to open-source when they're not really sure where to start, Gitter is the most straightforward way to jump in.  All you need is a Github account, and you're part of the group and ready to go.  

IRC might be intimidating for some (especially those that have never been part of open-source before), and Slack, while having good Github integration, is still one more step removed from the project repos.

**Comment by naroga** [comment]
@NoodlesNZ, there hasn't been any relevant activity on Gitter either. There wasn't anything worth discussing so far. Things should change from the 10th on.

If it boils down to Gitter/Slack, I'll have to ask if any of the two allow for 'public' chatrooms. I think making the channel private to members-only is odd for an opensource group. Even PHP internals make all conversation available for third-party (even the mailing lists have public archives). They even let outsiders (as myself) pitch in.

So far, I haven't been able to get into Slack because it requires an invite for our channel. If that's the norm, I'm with @dersam and will vote for Gitter.

Also, I'll be on IRC for general conversation with Jordan. Gitter spams everyone with an email, and that refrains me from asking silly things like 'how are you doing?'.

**Comment by matthewtrask** [comment]
@naroga Slack just requires you to register your email for the group. 

Id rather use Slack as a whole, even though IRC is one of my favorite messengers.

**Comment by naroga** [comment]
@rocketpastsix, this is what I get when trying to access phpjubilee.slack.com:

> Sorry, you may not have an account on this team. Get a list of teams associated with your email address.

**Comment by matthewtrask** [comment]
did you register the channel on slack already?

**Comment by JordanRL** [comment]
So Slack allows anyone to join, but it costs $8 per user per month to access that tier. I prefer Slack to Gitter as a tool, but I'm not really prepared to pay a few hundred per month for everyone to use it.

**Comment by matthewtrask** [comment]
Ive never paid anything and Im in a lot of slack channels. Unless their business model changed in the past few months, Ive never heard of that before.

**Comment by JordanRL** [comment]
That's probably because they charge the organization per user, instead of the user themselves. I had to deal with this at the last startup I worked at as well.

**Comment by naroga** [comment]
@rocketpastsix, someone else did.

> To start using Slack, you'll need to be invited by your team administrator.

I really dislike that idea. And it looks like we need the 'Plus' plan to allow guests, and the 'Plus' plan costs $8/month.

**Comment by JordanRL** [comment]
Well, I actually can turn off invitation only (@saji89 made me an org admin on slack), but then it will only allow "registrations" from email domains that I whitelist.

EDIT:

Oh, and Slack specifically disallows you from doing this from the main free email providers like gmail.com and yahoo.com

**Comment by naroga** [comment]
> it will only allow "registrations" from email domains that I whitelist

Which will still block out the curious... 

"this is an open source project, but we have a closed chat channel and you will not be able to follow the things we talk about".

@rocketpastsix has recommended Google Groups and I think it's an awesome suggestion. It aggregates conversation by topic, I can use from my email and it keeps everything logged.

**Comment by JordanRL** [comment]
Google groups is basically the same as a mailing list from the 1990s. Now, I have nothing against mailing lists, but surely there is an easier to use form of communication that we can all agree on.

**Comment by JordanRL** [comment]
Alright, this is the decision I would make if it's left entirely to me:
1. Developer conversation and chat occurs in the IRC room (#phpjubliee on freenode). The room is publicly accessible, and unrestricted.
2. Long form communication, and the main public discussion (that is, those with the general public who probably don't want to go through much trouble to ask a question or something like that), take place on the PHPJubilee subreddit at: http://www.reddit.com/r/phpjubilee

**Comment by matthewtrask** [comment]
+1
